name: Sync Fork

on:
  push:
    branches:
      - "sync-fork"
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your forked repository
        uses: actions/checkout@v4
        with:
          repository: FishDontExist/pactus
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/pactus-project/pactus.git
          git fetch upstream

      - name: Sync with upstream/main
        run: |
          git checkout main
          git merge upstream/main
          git push origin main

      - name: Clean up
        run: |
          git remote remove upstream
